version: '3'
services:
  worker1:
    build: ./app1
    ports:
      - "8001:8000"
  worker2:
    build: ./app2
    ports:
      - "8002:8000"
  worker3:
    build: ./app3
    ports:
      - "8003:8000"      
  data:
    build: ./data
    volumes:
      - ./data/data.csv:/data/data.csv
    ports:
      - "8004:8000"   
  redis:
    image: redis:alpine
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - worker1
      - worker2
      - worker3
